language: ruby
rvm:
- ruby-head
- 2.1.5
- 2.1.4
- 2.1.3
- 2.1.2
- 2.1.1
- 2.0.0
- 1.9.3
- 1.9.2
- 1.8.7
- jruby-head
- jruby-19mode
- jruby-18mode
- rbx-2.1.1
- ree
matrix:
  allow_failures:
  - rvm: 1.8.7
  - rvm: jruby-head
  - rvm: jruby-19mode
  - rvm: jruby-18mode
  - rvm: rbx-2.1.1
  - rvm: ree
